version: '3'
services:
  postgres:
    image: 'postgres:14.5'
    container_name: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "businesseval"
    #   PGDATA: /data/postgres
    # volumes:
    #    - './db:/data/postgres'
    ports:
      - '5432:5432'
    restart: unless-stopped

  api:
    build: ./business-eval
    links:
      - postgres
    container_name: business_eval
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=5432
      - DB_NAME=businesseval
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_USER_PASSWORD=12345678
    depends_on:
      - postgres